enable_damage = true
creative_mode = false
mod_storage_backend = sqlite3
auth_backend = sqlite3
backend = sqlite3
player_backend = sqlite3
gameid = minetest
world_name = Test (web)
server_announce = false
load_mod_web3_bridge = mods/web3_bridge
