window_maximized = true
screen_h = 2019
screen_w = 3840
port = 30000
enable_server = true
enable_damage = true
creative_mode = false
mainmenu_last_selected_world = 9
menu_last_game = minetest
dpi_change_notifier = 17
name = Name123
server_announce = false
secure.http_mods = web3_bridge


world_config_selected_mod = 24
fast_move = true
free_move = true
noclip = true
mute_sound = true


enable_fog = false
