window_maximized = true
screen_h = 991
screen_w = 1920
port = 30000
enable_server = true
enable_damage = true
creative_mode = false
mainmenu_last_selected_world = 6
menu_last_game = minetest
dpi_change_notifier = 13
name = Name123
server_announce = false
secure.http_mods = web3_bridge


world_config_selected_mod = 7
fast_move = true
free_move = true
noclip = true
mute_sound = true


enable_fog = false
